### ISSUE TITLE
crash  1.20.1 forge 47.2.0

### ISSUE THREAD

**Issue by Thunderrock424242** [ghen-git/Thirst-Mod#107]
spark dev told me its your issue
[latest.log](https://github.com/ghen-git/Thirst-Mod/files/14390601/latest.log)

**Comment by mlus-asuka** [comment]
Caused by: java.lang.IllegalArgumentException: Cannot set property IntegerProperty{name=layers, clazz=class java.lang.Integer, values=[0, 1, 2, 3, 4, 5, 6, 7, 8]} to -1 on Block{immersive_weathering:spruce_leaf_pile}, it is not an allowed value
	at net.minecraft.world.level.block.state.StateHolder.m_61124_(StateHolder.java:130) ~[client-1.20.1-20230612.114412-srg.jar%231042!/:?]
	at com.ordana.immersive_weathering.blocks.LeafPileBlock.m_213898_(LeafPileBlock.java:249) ~[immersive_weathering-1.20.1-2.0.0-forge.jar%23795!/:?]
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_222972_(BlockBehaviour.java:762) ~[client-1.20.1-20230612.114412-srg.jar%231042!/:?]
	at net.minecraft.server.level.ServerLevel.redirect$cdp000$redirectBlockStateTick(ServerLevel.java:6658) ~[client-1.20.1-20230612.114412-srg.jar%231042!/:?]

nope,it's not us as well. The log point to immersive weathering
