### ISSUE TITLE
Error Rendering Thirst Overlay

### ISSUE THREAD

**Issue by Corrinedev** [ghen-git/Thirst-Mod#129]
**Whenever I die every texture in the game, overlays, modded, EVERYTHING becomes blue. The console (clientside not serverside) also gets spammed with this error message**

[10/06/2024 19:49:16 PM] [Render thread/ERROR] Error rendering overlay 'thirst:thirst_level'
[10/06/2024 19:49:16 PM] 	at TRANSFORMER/thirst@1.20.1-1.3.7/dev.ghen.thirst.foundation.gui.ThirstBarRenderer.lambda$static$0(ThirstBarRenderer.java:44)
[10/06/2024 19:49:16 PM] 	at TRANSFORMER/forge@47.3.1/net.minecraftforge.client.gui.overlay.ForgeGui.lambda$render$0(ForgeGui.java:126)
[10/06/2024 19:49:16 PM] 	at MC-BOOTSTRAP/com.google.common@31.1-jre/com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422)
[10/06/2024 19:49:16 PM] 	at TRANSFORMER/forge@47.3.1/net.minecraftforge.client.gui.overlay.ForgeGui.m_280421_(ForgeGui.java:121)
[10/06/2024 19:49:16 PM] 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:945)
[10/06/2024 19:49:16 PM] 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146)
[10/06/2024 19:49:16 PM] 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718)
[10/06/2024 19:49:16 PM] 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.main.Main.main(Main.java:218)
[10/06/2024 19:49:16 PM] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[10/06/2024 19:49:16 PM] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[10/06/2024 19:49:16 PM] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[10/06/2024 19:49:16 PM] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[10/06/2024 19:49:16 PM] 	at MC-BOOTSTRAP/fmlloader@1.20.1-47.3.1/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111)
[10/06/2024 19:49:16 PM] 	at MC-BOOTSTRAP/fmlloader@1.20.1-47.3.1/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99)
[10/06/2024 19:49:16 PM] 	at MC-BOOTSTRAP/fmlloader@1.20.1-47.3.1/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25)
[10/06/2024 19:49:16 PM] 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
[10/06/2024 19:49:16 PM] 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
[10/06/2024 19:49:16 PM] 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
[10/06/2024 19:49:16 PM] 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:108)
[10/06/2024 19:49:16 PM] 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
[10/06/2024 19:49:16 PM] 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
[10/06/2024 19:49:16 PM] 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
[10/06/2024 19:49:16 PM] 	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)

**[latest.log](https://github.com/user-attachments/files/15780621/latest.log)**

**Comment by Corrinedev** [comment]
Nevermind. i remove the mod and the texture wierdness is still there anytime i die, i am genuinely confused

**Comment by Corrinedev** [comment]
closed not this mod's fault
