### ISSUE TITLE
[1.19.2]启动失败错误报告

### ISSUE THREAD

**Issue by BL4CKLOTU5www** [ghen-git/Thirst-Mod#80]
版本为1.19.2，mod版本为1.3.4，在与远古酿造系统重置版同时启动时出现该状况（疑似冲突，但是报告里出现的都是这边的mod）
![1](https://github.com/ghen-git/Thirst-Mod/assets/124428904/44b0a9f2-348a-4a40-979c-98c4e0d53cd8)
以下为错误报告：
_-- Head --
Thread: Render thread
Suspected Mod:
	Thirst was Taken (thirst), Version: 1.19.2-1.3.4
		Issue tracker URL: https://github.com/ghen-git/Thirst-Mod/issues
		at TRANSFORMER/thirst@1.19.2-1.3.4/dev.ghen.thirst.content.purity.WaterPurity.registerDispenserBehaviours(WaterPurity.java:638)
Stacktrace:
	at dev.ghen.thirst.content.purity.WaterPurity.registerDispenserBehaviours(WaterPurity.java:638) ThirstWasTaken-1.19.2-1.3.4.jar%23205!/:1.19.2-1.3.4] {re:mixin,re:classloading,pl:eventbus:A}
-- MOD thirst --
Details:
	Mod File: /C:/Users/130/Desktop/130/Minecraft1.19.2/.minecraft/versions/1.19.2-Forge_43.3.5/mods/ThirstWasTaken-1.19.2-1.3.4.jar
	Failure message: Thirst was Taken (thirst) encountered an error during the common_setup event phase
		java.lang.ClassCastException: class net.minecraft.core.dispenser.DefaultDispenseItemBehavior cannot be cast to class net.minecraft.core.dispenser.OptionalDispenseItemBehavior (net.minecraft.core.dispenser.DefaultDispenseItemBehavior and net.minecraft.core.dispenser.OptionalDispenseItemBehavior are in module minecraft@1.19.2 of loader 'TRANSFORMER' @3856d0cb)
	Mod Version: 1.19.2-1.3.4
	Mod Issue URL: https://github.com/ghen-git/Thirst-Mod/issues
	Exception message: java.lang.ClassCastException: class net.minecraft.core.dispenser.DefaultDispenseItemBehavior cannot be cast to class net.minecraft.core.dispenser.OptionalDispenseItemBehavior (net.minecraft.core.dispenser.DefaultDispenseItemBehavior and net.minecraft.core.dispenser.OptionalDispenseItemBehavior are in module minecraft@1.19.2 of loader 'TRANSFORMER' @3856d0cb)
Stacktrace:
	at dev.ghen.thirst.content.purity.WaterPurity.registerDispenserBehaviours(WaterPurity.java:638) ThirstWasTaken-1.19.2-1.3.4.jar%23205!/:1.19.2-1.3.4] {re:mixin,re:classloading,pl:eventbus:A}
	at dev.ghen.thirst.content.purity.WaterPurity.init(WaterPurity.java:85) ThirstWasTaken-1.19.2-1.3.4.jar%23205!/:1.19.2-1.3.4] {re:mixin,re:classloading,pl:eventbus:A}
	at dev.ghen.thirst.Thirst.commonSetup(Thirst.java:71) ThirstWasTaken-1.19.2-1.3.4.jar%23205!/:1.19.2-1.3.4] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.3.jar%23134!/:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252) ~[eventbus-6.0.3.jar%23134!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%23134!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%23134!/:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:114) ~[javafmllanguage-1.19.2-43.3.5.jar%23423!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:122) ~[fmlcore-1.19.2-43.3.5.jar%23422!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}_
不知道是什么状况总之先发个issue了ovo

**Comment by mlus-asuka** [comment]
@ghen-git 
maybe change WaterPurity:638 from
```java
OptionalDispenseItemBehavior bottleDefaultBehaviour = (OptionalDispenseItemBehavior) ReflectionUtil.MethodReflection(getDispenseMethod, Blocks.DISPENSER, new ItemStack(Items.GLASS_BOTTLE));
```
to
```java
 DispenseItemBehavior bottleDefaultBehaviour = (DispenseItemBehavior) ReflectionUtil.MethodReflection(getDispenseMethod, Blocks.DISPENSER, new ItemStack(Items.GLASS_BOTTLE));
```
to fix it.

**Comment by ghen-git** [comment]
i changed the code, but i didn't understand which mod caused the crash, i couldn't find mods named Ancient Brewing

**Comment by mlus-asuka** [comment]
> i changed the code, but i didn't understand which mod caused the crash, i couldn't find mods named Ancient Brewing

https://github.com/edebeawa/BetaBrewingSystem
